plugins {
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '3.4.1'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: '3.4.1'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-tomcat', version: '3.4.1'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: '3.4.1'
    implementation group: 'org.apache.tomcat.embed', name: 'tomcat-embed-jasper', version: '11.0.2'
    implementation 'org.apache.commons:commons-text:1.11.0'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '3.5.1'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'     
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3' 
}

test {
    useJUnitPlatform()
}
