# URL della connessione al DB con SSL attivo (usa sslMode=TRUST se vuoi bypassare la validazione completa)
spring.datasource.url=jdbc:mariadb://localhost:3306/reviewhub_db?sslMode=TRUST

# Credenziali del DB
spring.datasource.username=admin
spring.datasource.password=#ZPe*Ku!

# Driver da usare (solo il driver MariaDB, non ci devono essere riferimenti al driver MySQL)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configurazioni di Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Imposta esplicitamente il Dialect per MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

# Configurazione di HikariCP (usa sslMode al posto dei vecchi parametri)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.data-source-properties.sslMode=TRUST

# Configurazione del server
server.port=8888
server.address=0.0.0.0

# Configurazione SSL per il server Spring Boot (attivato HTTPS)
server.ssl.key-store=classpath:server.keystore
server.ssl.key-store-password=81MRDigfICg9
server.ssl.key-alias=server-alias
server.ssl.enabled=true
server.http2.enabled=true

# Disabilita HTTP (opzionale, solo per forzare l'uso di HTTPS)
# server.http.enabled=false

# Configurazione di HTTPs (se necessario per HTTPS)
spring.webflux.server.use-https=true
spring.main.web-application-type=servlet
