package org.example.models;

public enum Materia {
    MATEMATICA,
    ITALIANO,
    CHIMICA,
    FISICA,
    STORIA,
    GESTIONE_PROGETTO_ED_ORGANIZZAZIONE_IMPRESA,
    DIRITTO_ECONOMIA,
    TPSIT,
    TTRG,
    INGLESE,
    EDUCAZIONE_FISICA
}